### ISSUE TITLE
Not working with Collabora/LOOL 7.x

### ISSUE THREAD

**Issue by mmaridev** [learnweb/moodle-mod_collabora#23]
Currently testing with version 7.0 and apparently not working.

That's the log from Docker:

```
wsd-00006-00036 2020-09-04 10:29:35.888793 [ websrv_poll ] ERR  Unknown resource: /lool/https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https://moodle.domain.tld/mod/collabora/callback.php/wopi/files/69_0&compat=/ws GWebSocket path: 10 'lool' 'https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https:' 'moodle.domain.tld' 'mod' 'collabora' 'callback.php' 'wopi' 'files' '69_0&compat=' 'ws'| wsd/LOOLWSD.cpp:2412
wsd-00006-00036 2020-09-04 10:29:36.763142 [ websrv_poll ] ERR  Unknown resource: /lool/https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https://moodle.domain.tld/mod/collabora/callback.php/wopi/files/69_0&compat=/ws GWebSocket path: 10 'lool' 'https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https:' 'moodle.domain.tld' 'mod' 'collabora' 'callback.php' 'wopi' 'files' '69_0&compat=' 'ws'| wsd/LOOLWSD.cpp:2412
wsd-00006-00036 2020-09-04 10:29:52.081939 [ websrv_poll ] ERR  Unknown resource: /lool/https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https://moodle.domain.tld/mod/collabora/callback.php/wopi/files/69_0&compat=/ws GWebSocket path: 10 'lool' 'https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https:' 'moodle.domain.tld' 'mod' 'collabora' 'callback.php' 'wopi' 'files' '69_0&compat=' 'ws'| wsd/LOOLWSD.cpp:2412
wsd-00006-00036 2020-09-04 10:30:46.153221 [ websrv_poll ] ERR  Unknown resource: /lool/https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https://moodle.domain.tld/mod/collabora/callback.php/wopi/files/69_0&compat=/ws GWebSocket path: 10 'lool' 'https%3A%2F%2Fmoodle.domain.tld%2Fmod%2Fcollabora%2Fcallback.php%2Fwopi%2Ffiles%2F69_0%3Faccess_token%3D902cd64bdc99%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https:' 'moodle.domain.tld' 'mod' 'collabora' 'callback.php' 'wopi' 'files' '69_0&compat=' 'ws'| wsd/LOOLWSD.cpp:2412
```

**Comment by kratzersmz** [comment]
@mmaridev : are there any news on this?

same issue here. Using dockered version too

greets

**Comment by Dagefoerde** [comment]
Thanks for reporting this issue. The logs report something in `wsd/LOOLWSD.cpp:2412`, so that is Collabora/LibreOffice and not Moodle. I suppose that the people over there will be able to provide more help. 

Anyway, what is Collabora/LOOL 7.x? Where did you get the Docker image from, and which one did you use specifically? After all, I believe Collabora celebrated the launch of 4.2 only recently (https://twitter.com/CollaboraOffice/status/1314120873520005120) and LibreOffice Online seems to be at 6.2 (https://hub.docker.com/r/cibsoftware/libreoffice-online/tags). Any details on your setup would be greatly appreciated in order to narrow it down! Thanks :)

**Comment by kratzersmz** [comment]
@Dagefoerde thanx for responding....

here you see my docker-compose.yml  ---> this is working with several nexcloud instances fine....but moodle not ehh

That's the image for libreoffice 7.0, docker image is based on work of https://wiki.documentfoundation.org/Development/BuildingOnline 

```
services:
  frontproxy:
    restart: always
    image: jwilder/nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs-volume:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"

  nginx-letsencrypt-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "certs-volume:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "frontproxy"

  collabora:
    image: kratzersmz/libreoffice-online:7-0-2020-08-18
    restart: unless-stopped
    hostname: office.domain.de
    environment:
      - username=admin1
      - password=MenschMeier
      - domain=cloud.domain.de|cloud.domain2.de|cloud.domain3.de
      - VIRTUAL_HOST=office.domain.de
      - LETSENCRYPT_HOST=office.domain.de
      - LETSENCRYPT_EMAIL=webmaster@office.domain.de
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    networks:
      - frontproxy_default
      - default

networks:
  frontproxy_default:
    external: true

volumes:
  certs-volume:
```
